name: Publish docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ${{vars.RUNNER}}
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/dependencies
        with:
          nodeVersion: ${{ vars.NODE_LTS }}

      - name: Build
        run: cd packages/docs && yarn build

      - name: Generate docs artifact
        uses: actions/upload-artifact@v6
        with:
          name: docs-artifact
          path: packages/docs/dist
          if-no-files-found: error

      - name: Checkout gh-pages
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          ref: gh-pages

      - name: Clear directory
        run: |
          rm -rf $(ls -A | grep -v .git)

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: docs-artifact

      - name: Push changes
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Automated deploy"
          git push
